version: '3'

vars:
  ONTOLOGY: coy
  BASE_URL: https://schema.coypu.org/global
  JOD_TITLE: "coy: CoyPu Ontology"
  DOCU_PATH: .
  JOD_IMAGE: ghcr.io/eccenca/jod:main
  DOCKER_DIRS: "-v ./coy.ttl:/data/ontology.ttl -v ./_site:/data/_site"

tasks:

  default:
    - task: docu:build
      vars: { DOCU_PATH: '{{.DOCU_PATH}}' }

  clean:
    desc: Remove generated artifacts
    cmds:
      - rm -r ./_site

  docu:build:
    desc: Build the HTML documentation page for an ontology.
    cmds:
      - mkdir -p {{.DOCU_PATH}}/_site
      - docker run --rm -e JOD_URL={{.BASE_URL}} -e JOD_TITLE="{{.JOD_TITLE}}" -e JOD_RESTRICTION_URL=True {{.DOCKER_DIRS}} {{.JOD_IMAGE}}

  docu:serve:
    - python -m http.server --directory docu-ontology/_site

  helper:check_turtle:
    desc: Verify the correct syntax of a Turtle file.
    cmds:
      - '{{ .RAPPER }} -i turtle -c {{.FILE}}.ttl'
