version: '3'

vars:
  ONTOLOGY: main
  RAPPER: rapper
  DOCU_PATH: .

tasks:

  default:
    - task: helper:check_turtle
      vars: { FILE: '{{.ONTOLOGY}}' }
    - task: docu:build
      vars: { DOCU_PATH: '{{.DOCU_PATH}}' }

  clean:
    desc: Remove generated artifacts
    cmds:
      - rm -r ./_site

  docu:build:
    desc: Build the HTML documentation page for an ontology.
    cmds:
      - task: helper:install_jekyll
      - bundle exec jekyll build

  docu:serve:
    - python -m http.server --directory docu-ontology/_site

  helper:check_turtle:
    desc: Verify the correct syntax of a Turtle file.
    cmds:
      - '{{ .RAPPER }} -i turtle -c {{.FILE}}.ttl'

  helper:install_jekyll:
    desc: Install Jekyll and JekyllRDF
    cmds:
      - bundle install
